title:               Mickey
tagline:             A Spelt Theme
description: >
  A short description for your site
url:                 "http://example.com"
baseurl:             ""
rss:                 feed.xml # path to RSS feed

# Paths
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'

# Comments
disqus_enabled:      false
disqus:              disqus_shortname # get it on https://disqus.com/admin/

# Social
icon:                "path/to/site/icon" # e.g. /assets/img/icon.png [best 300px X 300px]

author:
  name:           	 Your Name
  url:            	 your site url
  facebook:          username
  twitter:           nielsify
  google_plus:       username
  linkedin:          username
  dribbble:          username
  pinterest:         username
  kiva:              username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id
